### ISSUE TITLE
Remove gcc package from environment (gssha currently depends on gcc)

### ISSUE THREAD

**Issue by ceball** [pyviz/EarthSim#102]
As far as I can tell, the gcc package is deprecated (?around the time of Anaconda Distribution 5; I'm not sure how someone's supposed to be aware of that, but that's a different issue...). 

In #97, you can see that installing gcc is clobbering libgcc-ng (which then results in various subsequent problems). 

gssha (https://anaconda.org/erdc/gssha) has a runtime dependency on gcc; is it possible to remove that? Or change it to e.g. libgcc-ng? Or if a compiler's required, I think it's now packages with the platform in the name, like gcc_linux-64 etc.

**Comment by ceball** [comment]
Using conda-build 3, it should be possible to replace

```
requirements:
  build:
    - vc14  # [win and py>=35]
    - gcc # [unix]
    - ...
  run:
    - vc14  # [win and py>=35]
    - gcc # [unix]
    - ...
```

with

```
requirements:
  build:
    - {{ compiler('c') }}
    - ...
  run:
    - ...
```
