### ISSUE TITLE
filigree: boost (conda-forge) vs libboost (defaults)

### ISSUE THREAD

**Issue by ceball** [pyviz/EarthSim#106]
We currently seem to be bringing both into the environment, resulting in clobber errors.

**Comment by ceball** [comment]
filigree's recipe includes:

```
requirements:
  build:
    - ...
    - libboost # [linux]
    - boost-cpp # [not linux]
  run:
    - libboost # [linux]
    - boost-cpp # [not linux]
    - ...
```

Could it just be `boost-cpp` on all platforms?

Note that libfiligree's recipe includes:

```
requirements:
  build:
    - ...
    - boost-cpp
  run:
    - boost-cpp
```

Because libboost only exists on defaults, the combination of the above two recipes with the conda-forge channel (which we must use for earthsim) results in getting boost from both defaults and conda-forge...
